---
supabase_internal: true
ebssurrogate_mode: true
async_mode: true

postgres_major:
  - "15"
  - "17"
  - orioledb-17

# Full version strings for each major version
postgres_release:
  postgresorioledb-17: "17.6.0.040-orioledb"
  postgres17: "17.6.1.083"
  postgres15: "15.14.1.083"

# Non Postgres Extensions
pgbouncer_release: 1.25.1
pgbouncer_release_checksum: sha256:6e566ae92fe3ef7f6a1b9e26d6049f7d7ca39c40e29e7b38f6d5500ae15d8465

# The checksum can be found under "Assets", in the GitHub release page for each version.  
# The binaries used are: ubuntu-aarch64 and linux-static.
# https://github.com/PostgREST/postgrest/releases
postgrest_release: 14.1
postgrest_arm_release_checksum: sha256:68885d936873059b946afadaae697467daedacd7d8e697a80b7f0f6881c9c92f
postgrest_x86_release_checksum: sha256:bdab6ab3389ca0d6c1f3b8363491674dbca71875c3f30261d92d8fecdde35277

gotrue_release: 2.186.0
gotrue_release_checksum: sha1:94cd063227e01dcc71811aa63ecdd996d0c0419c

aws_cli_release: 2.23.11

salt_minion_version: 3007

golang_version: 1.22.11
golang_version_checksum:
  arm64: sha256:0fc88d966d33896384fbde56e9a8d80a305dc17a9f48f1832e061724b1719991
  amd64: sha256:9ebfcab26801fa4cf0627c6439db7a4da4d3c6766142a3dd83508240e4f21031

envoy_release: 1.28.0
envoy_release_checksum: sha1:b0a06e9cfb170f1993f369beaa5aa9d7ec679ce5
envoy_hot_restarter_release_checksum: sha1:6d43b89d266fb2427a4b51756b649883b0617eda

kong_release_target: focal
kong_deb: kong_2.8.1_arm64.deb
kong_deb_checksum: sha1:2086f6ccf8454fe64435252fea4d29d736d7ec61

nginx_release: 1.22.0
nginx_release_checksum: sha1:419efb77b80f165666e2ee406ad8ae9b845aba93

postgres_exporter_release: "0.15.0"
postgres_exporter_release_checksum:
  arm64: sha256:29ba62d538b92d39952afe12ee2e1f4401250d678ff4b354ff2752f4321c87a0
  amd64: sha256:cb89fc5bf4485fb554e0d640d9684fae143a4b2d5fa443009bd29c59f9129e84

adminapi_release: "0.95.1"
adminmgr_release: "0.32.3"
supabase_admin_agent_release: 1.6.0
supabase_admin_agent_splay: 30s

vector_x86_deb: https://packages.timber.io/vector/0.48.X/vector_0.48.0-1_amd64.deb
vector_arm_deb: https://packages.timber.io/vector/0.48.X/vector_0.48.0-1_arm64.deb
