name: Check shell scripts

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.merge_group.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: supabase/postgres/.github/actions/shared-checkout@HEAD
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2001 -e SC2002 -e SC2143
      with:
        scandir: './ansible/files/admin_api_scripts'

    - name: Run ShellCheck on pg_upgrade scripts
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2001 -e SC2002 -e SC2143
      with:
        scandir: './ansible/files/admin_api_scripts/pg_upgrade_scripts'
