name: Release Migrations - Prod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Guard
        run: |
          if [ $GITHUB_REF != 'refs/heads/develop' ]; then
            echo "This action can only be run on the develop branch"
            exit 1
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Checkout repo
        uses: supabase/postgres/.github/actions/shared-checkout@HEAD

      - name: Merging migration files
        run: cat $(ls -1) > ../migration-output.sql
        working-directory: ${{ github.workspace }}/migrations/db/migrations

      - name: configure aws credentials - prod
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
          aws-region: "ap-southeast-1"

      - name: Deploy to S3 prod
        shell: bash
        run: aws s3 sync migrations/db s3://$AWS_S3_BUCKET/migrations/db --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PG_INIT_SCRIPT_S3_BUCKET_PROD }}
